stages:
  - build
  - deploy

variables:
  REGISTRY: 192.168.122.1:5000
  IMAGE_NAME: myapp
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build-app:
  stage: build
  image: docker:24
  script:
    - cd app
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-nginx:
  stage: build
  image: docker:24
  script:
    - cd nginx
    - docker build -t $REGISTRY/nginx:$IMAGE_TAG .
    - docker push $REGISTRY/nginx:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: cytopia/ansible:latest-tools
  before_script:
    - mkdir -p ~/.ssh
    - echo "$ENCODED_SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 192.168.122.100 >> ~/.ssh/known_hosts
  script:
    - >
      ansible-playbook -i ansible/inventory ansible/site.yml
      --extra-vars "registry=$REGISTRY image_name=$IMAGE_NAME image_tag=$IMAGE_TAG"
      --extra-vars "app_secret_message=$SECRET_MESSAGE app_username=$USERNAME app_password=$PASSWORD"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
