stages:
  - build
  # - deploy

variables:
  REGISTRY: 192.168.122.1:5000
  IMAGE_NAME: myapp
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:24
  script:
    - cd app
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# deploy:
#   stage: deploy
#   image: cytopia/ansible:latest
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo "$ENCODED_SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - ssh-keyscan -H 192.168.122.100 >> ~/.ssh/known_hosts
#   script:
#     - ansible-playbook -i ansible/inventory ansible/deploy.yml --extra-vars "image_tag=$IMAGE_TAG registry=$REGISTRY image_name=$IMAGE_NAME"
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
