- name: Update all the systems
  hosts: webservers
  roles:
    - base

- name: Install and configure dependencies
  hosts: webservers
  roles:
    - docker-setup

- name: Deploy the app
  hosts: webservers
  roles:
    - app-deploy
